packages:
  - apps/*
  - packages/*
  - e2e/*

catalog:
  '@types/node': ^22.0.0
  '@types/react': ^18.3.0
  '@types/react-dom': ^18.3.0
  next: ^15.5.2
  react: ^18.3.0
  react-dom: ^18.3.0
  tailwindcss: 3.4.1
  tsx: 4.20.3
  typescript: ~5.9.0
  valtio: ^1.12.0
  vite: ^7.1.11
  vitest: ^3.2.0
  zod: ^3.25.76

minimumReleaseAgeExclude:
  - '@paybilldev/*'
  - paybill

onlyBuiltDependencies:
  - paybill

ignoredBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - msw

minimumReleaseAge: 10080

